### ISSUE TITLE
armeabi会出错

### ISSUE THREAD

**Issue by 350030173** [bmax121/sktrace#1]
{'type': 'error', 'description': 'Error: compilation failed: module.c:51: warning: cast between pointer and integer of 
different size\nmodule.c:51: warning: cast between pointer and integer of different size\nmodule.c:54: warning: cast 
between pointer and integer of different size\nmodule.c:55: warning: cast between pointer and integer of different 
size\nmodule.c:60: warning: cast between pointer and integer of different size', 'stack': 'Error: compilation 
failed: module.c:51: warning: cast between pointer and integer of different size\nmodule.c:51: warning: cast 
between pointer and integer of different size\nmodule.c:54: warning: cast between pointer and integer of different 
size\nmodule.c:55: warning: cast between pointer and integer of different size\nmodule.c:60: 
warning: cast between pointer and integer of different size\n   
at <eval> (/script1.js:98)', 'fileName': '/script1.js', 'lineNumber': 98, 'columnNumber': 1}Tracing. Press any key to quit...

**Comment by bmax121** [comment]
frida stalker 暂时不支持 arm 32 bit
